[34m[1mwandb[0m: [33mWARNING[0m Config item 'loss_fn' was locked by 'sweep' (ignored update).
Traceback (most recent call last):
  File "/home/autrio/college-linx/SMAI/smai-m24-assignments-Autrio/assignments/3/2/2/3.py", line 93, in run
    model = mlp.Model(config)
  File "/home/autrio/college-linx/SMAI/smai-m24-assignments-Autrio/models/MLP/MLP2.py", line 333, in __init__
    self.logger = params["logger"]
  File "/home/autrio/.local/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 130, in __getitem__
    return self._items[key]
KeyError: 'logger'
